### ISSUE TITLE
Whats happening here?

### ISSUE THREAD

**Issue by kwaazaar** [tillig/ps-bash-completions#7]
When I press tab, I get weird characters. What is happening:

kubectl W^@i^@n^@d^@o^@w^@s^@ ^@S^@u^@b^@s^@y^@s^@t^@e^@m^@ ^@f^@o^@r^@ ^@L^@i^@n^@u^@x^@ ^@h^@a^@s^@ ^@n^@o^@ ^@i^@n^@s^@t^@a^@l^@l^@e^@d^@ ^@d^@i^@s^@t^@r^@i^@b^@u^@t^@i^@o^@n^@s^@.^@

**Comment by tillig** [comment]
Great question. If I can't reproduce it, I can't troubleshoot it. [The README has some troubleshooting tips.](https://github.com/tillig/ps-bash-completions/blob/master/README.md)

Looking at the plain characters in there, the message shows, "Windows sUbsystem for linUx hAs no instAlled distribUtions." That's odd capitalization; I can't tell if it's something you copy/pasted or manually typed. The message is pretty clear, though. The cmdlet found bash and thinks it's attached to Windows Subsystem for Linux, but you don't have any installed distribution.

If you look at the [bash detection logic in the script](https://github.com/tillig/ps-bash-completions/blob/8e20d54119f208f0448909587bbea59784ace4c5/PSBashCompletions/PSBashCompletions.psm1#L98), Powershell runs `Get-Command bash` to locate where `bash` is on your Windows system. **Try that.** If you have Windows Subsystem for Linux installed, you'll see something like:

```
 PS> get-command bash

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     bash.exe                                           10.0.17... C:\WINDOWS\system32\bash.exe
```

Notice `bash.exe` is in the Windows folder. This is really just a pass-through to Windows Subsystem for Linux. If you _run that `bash.exe`_ it's going to try to invoke it in WSL. However, based on the message, while you have WSL enabled on your machine, you _don't_ have any Linux distribution installed yet.

Go to the Windows store and install a Linux distribution. [My favorite choice is the Ubuntu distribution.](https://www.microsoft.com/store/productId/9NBLGGH4MSV6)

You may need to do some setup in there before it works. For example, I think the first time you fire it up you need to set up a user account in the distribution. Once that's working, you're set.

The other option is to disable WSL on your machine if you're not using it. That should remove the `bash.exe` from the Windows folder and allow the completions to find a different bash, like the one packaged with Git for Windows.
