### ISSUE TITLE
macOS and Linux support

### ISSUE THREAD

**Issue by TylerLeonhardt** [tillig/ps-bash-completions#8]
Right now this depends on GitBash. It'd be great if it could work crossplatform.

**Comment by tillig** [comment]
Either something has changed with a recent PR or I can't replicate it, but this does seem to work fine under PowerShell Core on MacOS using v1.2.2 of the PSBashCompletions module.

Note the bash that ships with MacOS is a stale version from 2007. You need to install a newer one using Homebrew - `brew install bash`

I updated the README to include that information.
