### ISSUE TITLE
Chances of supporting aws-vault

### ISSUE THREAD

**Issue by DefSol** [tillig/ps-bash-completions#9]
Hey @tillig, I came across this the other day and it's great. thanks for the effort. Once I sorted my line endings and text encodings it worked a treat.

Being in AWS land, I extensively use aws-vault as a means to manage keys & roles assumption. The aws-vault API is in the format `aws-vault exec <profile> -- <command>` where profile could change depending on the role I need to assume, and the command will always by kubectl (or alias)

Given the aws-vault API is somewhat static, would you think it's possible to be able to parse out the aws-vault command to figure out I'm actually calling kubectl and apply the auto-completion?

Be keen to help out if you think it's possible

Again many thanks for your efforts and learnt a new pattern for managing text-encoding and line endings in PowerShell

**Comment by tillig** [comment]
Yeah, this mechanism should work for any command that has a bash completion script available, including aws-vault. The key is getting that script, which isn't something I can help with.

This extension doesn't generate the completions, it uses completions generated elsewhere. Usually this comes from the CLI itself. A quick Google shows you may be able to do `aws-vault --completion-script-bash` and it'll generate it. If so, pipe that to a file and you're good.

If I found the wrong thing and you don't have an auto-generated completion file available, you'll have to write it. I've never written one by hand so can't offer advice, but again a Google search shows there are tutorials.

**Comment by DefSol** [comment]
Hey @tillig I checked the native behaviour in bash and it doesn't work there. I assume this would just work. thanks again
